# Generated by Django 5.2.1 on 2025-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='encryption_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
