# Generated by Django 5.2.1 on 2025-07-04 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_user_passcode_attempts_user_passcode_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_usd', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('price_btc', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('price_eth', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='wallet.account')),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='wallet.cryptocurrency')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('cryptocurrency', 'timestamp')},
            },
        ),
    ]
