# Generated by Django 5.2.1 on 2025-07-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
